version: "3.9"
services:
    php:
        container_name: ${APP_NAME}_server
        build: ./etc/php
        ports:
            - 80:80
        volumes:
            - ./app:/var/www/html
    database:
        image: mysql:5.7
        container_name: ${APP_NAME}_mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306